apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodscribe-backend
  namespace: prodscribe
  labels:
    app: prodscribe-backend
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prodscribe-backend
  template:
    metadata:
      labels:
        app: prodscribe-backend
        version: v1
    spec:
      containers:
      - name: backend
        image: prodscribe/backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: prodscribe-secrets
              key: database_url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: prodscribe-secrets
              key: jwt_secret
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: prodscribe-secrets
              key: openai_api_key
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: prodscribe-config
              key: redis_url
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: prodscribe-backend-service
  namespace: prodscribe
spec:
  selector:
    app: prodscribe-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: ClusterIP 