apiVersion: v1
kind: ConfigMap
metadata:
  name: prodscribe-config
  namespace: prodscribe
data:
  api_url: "https://api.prodscribe.com"
  redis_url: "redis://prodscribe-redis-service:6379"
  environment: "production"
  log_level: "info"
  cors_origin: "https://prodscribe.com,https://www.prodscribe.com" 